priceItem:
  price: 2000
xPriceItem:
  price: 400
userItemTemplate:
  userItemTemplate: 1435138575888
itemIcon:
  spriteUid: dc138502-5581-4287-97eb-8fff8b5650ff
order:
  index: 11
crystalsPurchaseUserRankRestriction:
  restrictionValue: 14
minDamageProperty:
  initialValue: 952.000
  finalValue: 952.000
maxDamageProperty:
  initialValue: 952.000
  finalValue: 952.000
chargeTimeProperty:
  initialValue: 1.000
  finalValue: 1.000
reloadTimeProperty:
  initialValue: 4.500
  finalValue: 4.500
damageWeakeningByTargetProperty:
  initialValue: 95.000
  finalValue: 95.000
impactProperty:
  initialValue: 6.000
  finalValue: 6.000
kickbackProperty:
  initialValue: 2.000
  finalValue: 2.000
visualProperties:
  mainProperties:
    - name: Damage
      normalizedValue: 1.0
    - name: Range
      normalizedValue: 1.00
    - name: FireRate
      normalizedValue: 0.20
  properties:
    - name: DPM
      initialValue: 10385
      finalValue: 10385
    - name: Damage
      initialValue: 952
      finalValue: 952
    - name: Charge Time
      initialValue: 1
      finalValue: 1
      format: 0
      unit: sec
    - name: Reload Time
      initialValue: 4.5
      finalValue: 4.5
      format: 0.0
      unit: sec
    - name: Piercing Damage Percent
      initialValue: 95
      finalValue: 95
      unit: percent
    - name: Impact
      initialValue: 6
      finalValue: 6
...
