entranceValidationRules:
  loginRegex: "^([a-zA-Z0-9]+[-_.]?)+[a-zA-Z0-9]$"
  loginSymbolsRegex: "^[a-zA-Z0-9-_.]+$"
  loginBeginingRegex: "^[a-zA-Z0-9].*$"
  loginEndingRegex: "^.*[a-zA-Z0-9]$"
  loginSpecTogetherRegex: "[-_.]{2,}"
  emailRegex: ".+@.+\\..+"
  discordUsernameRegex: "^(?!.*?\\.{2,})[a-z0-9_\\.]{2,32}$"
  passwordRegex: "^.*$"
  minLoginLength: 2
  maxLoginLength: 20
  minPasswordLength: 6
  maxPasswordLength: 20
  minEmailLength: 6
  maxEmailLength: 254
  minDiscordUsernameLength: 2
  maxDiscordUsernameLength: 32
  maxCaptchaLength: 12
