purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 300
aimingMinDamageProperty:
  initialValue: 450.000
  finalValue: 450.000
aimingMaxDamageProperty:
  initialValue: 1050.000
  finalValue: 1050.000
energyChargePerShotProperty: # UnloadEnergyPerQuickShot (value)
  initialValue: 0.429
  finalValue: 0.429
energyChargeSpeedProperty: # UnloadAimingEnergyPerSec (value), UnloadEnergyPerSec (value)
  initialValue: 0.134
  finalValue: 0.134
energyRechargeSpeedProperty: # ReloadEnergyPerSec (value)
  initialValue: 0.120
  finalValue: 0.120
reloadTimeProperty: # ReloadEnergyPerSec (1/value), CooldownIntervalSec (value)
  initialValue: 3.500
  finalValue: 3.500
temperatureHittingTimeProperty:
  initialValue: 10.000
  finalValue: 10.000
aimingVerticalAccelerationProperty:
  initialValue: 20.000
  finalValue: 20.000
aimingHorizontalAccelerationProperty:
  initialValue: 40.000
  finalValue: 40.000
aimingVerticalSpeedProperty:
  initialValue: 20.000
  finalValue: 20.000
aimingHorizontalSpeedProperty:
  initialValue: 40.000
  finalValue: 40.000
impactProperty:
  initialValue: 1.000
  finalValue: 1.000
aimingImpactProperty:
  initialValue: 6.000
  finalValue: 6.000
kickbackProperty:
  initialValue: 4.000
  finalValue: 4.000
deltaTemperaturePerSecondProperty:
  initialValue: 0.100
  finalValue: 0.100
temperatureLimitProperty:
  initialValue: 0.500
  finalValue: 0.500
heatDamageProperty:
  initialValue: 150
  finalValue: 150
unityAsset:
  reference:
    assetGuid: a32ef8afbd933ce479763e387bd752de
imageItem:
  spriteUid: 961531d2-0ba1-43ad-bdfb-13275c73b392
itemRarity:
  rarityType: COMMON
