priceItem:
  price: 0
xPriceItem:
  price: 0
userItemTemplate:
  userItemTemplate: 1433406776150
itemIcon:
  spriteUid: 4053fb51-0d28-4afb-97a4-c66ce972b375
order:
  index: 1
crystalsPurchaseUserRankRestriction:
  restrictionValue: 0
behaviorProperty: #1 - progression, 2 - crit, 3 - crit + random cooldown change
  initialValue: 1
  finalValue: 1
minDamageProperty:
  initialValue: 325
  finalValue: 325
maxDamageProperty:
  initialValue: 325
  finalValue: 325
reloadTimeProperty:
  initialValue: 1.300
  finalValue: 1.300
startDamageProgressionProperty:
  initialValue: 300
  finalValue: 300
maxDamageProgressionProperty:
  initialValue: 480
  finalValue: 480
damageProgressionDeltaProperty:
  initialValue: 25
  finalValue: 25
damageProgressionResetTimeSecProperty:
  initialValue: 3
  finalValue: 3
criticalDamageProperty:
  initialValue: 325.000
  finalValue: 325.000
startCriticalProbabilityProperty:
  initialValue: 0.200
  finalValue: 0.200
afterCriticalHitProbabilityProperty:
  initialValue: -0.500
  finalValue: -0.500
maxCriticalProbabilityProperty:
  initialValue: 0.950
  finalValue: 0.950
criticalProbabilityDeltaProperty:
  initialValue: 0.100
  finalValue: 0.100
maxDamageDistanceProperty:
  initialValue: 83.091
  finalValue: 83.091
minDamageDistanceProperty:
  initialValue: 128.261
  finalValue: 128.261
minDamagePercentProperty:
  initialValue: 52.174
  finalValue: 52.174
impactProperty:
  initialValue: 3.000
  finalValue: 3.000
kickbackProperty:
  initialValue: 3.000
  finalValue: 3.000
visualProperties:
  mainProperties:
    - name: Damage
      normalizedValue: 0.268
    - name: Range
      normalizedValue: 0.741
    - name: FireRate
      normalizedValue: 0.80
  properties:
    - name: DPM
      initialValue: 22300
      finalValue: 22300
    - name: Damage
      initialValue: 300
      finalValue: 300
    - name: MaxDamage
      initialValue: 480
      finalValue: 480
    - name: ProgressionDelta
      initialValue: 25
      finalValue: 25
    - name: Duration
      initialValue: 3
      finalValue: 3
      unit: sec
    - name: Reload Time
      initialValue: 1.3
      finalValue: 1.3
      format: 0.0
      unit: sec
    - name: Max Damage Distance
      initialValue: 83.1
      finalValue: 83.1
      format: 0.0
      unit: m
    - name: Attack Distance
      initialValue: 128.3
      finalValue: 128.3
      format: 0.0
      unit: m
    - name: Impact
      initialValue: 3.0
      finalValue: 3.0
      format: 0.0
...
