purchaseUpgradeLevelRestriction:
  restrictionValue: 0
purchaseUserRankRestriction:
  restrictionValue: 0
mountUpgradeLevelRestriction:
  restrictionValue: 0
mountUserRankRestriction:
  restrictionValue: 0
priceItem:
  price: 0
xPriceItem:
  price: 0
order:
  index: 300
damagePerSecondProperty:
  initialValue: 400.000
  finalValue: 400.000
healingProperty:
  initialValue: 330.000
  finalValue: 330.000
energyChargeSpeedProperty:
  initialValue: 0.125
  finalValue: 0.125
energyRechargeSpeedProperty:
  initialValue: 0.143
  finalValue: 0.143
selfHealingProperty:
  initialValue: 25.000
  finalValue: 25.000
increaseFriendTemperatureProperty:
  initialValue: 0.100
  finalValue: 0.100
decreaseFriendTemperatureProperty:
  initialValue: 0.100
  finalValue: 0.100
maxShotDistanceProperty:
  initialValue: 17.3
  finalValue: 17.3
unityAsset:
  reference:
    assetGuid: c1faba0d5248a3a4eb648f97fc32b4b0
imageItem:
  spriteUid: 10daa063-a952-4d45-a08a-a03b8e066754
itemRarity:
  rarityType: COMMON
