priceItem:
  price: 800
xPriceItem:
  price: 160
userItemTemplate:
  userItemTemplate: 1435910167704
itemIcon:
  spriteUid: 766f4b6f-d66c-4b9f-856c-ae13211d4b74
order:
  index: 4
crystalsPurchaseUserRankRestriction:
  restrictionValue: 5
damagePerSecondProperty:
  initialValue: 400.000
  finalValue: 400.000
healingProperty:
  initialValue: 330.000
  finalValue: 330.000
energyChargeSpeedProperty:
  initialValue: 0.125
  finalValue: 0.125
energyRechargeSpeedProperty:
  initialValue: 0.143
  finalValue: 0.143
selfHealingProperty:
  initialValue: 25.000
  finalValue: 25.000
increaseFriendTemperatureProperty:
  initialValue: 0.100
  finalValue: 0.100
decreaseFriendTemperatureProperty:
  initialValue: 0.100
  finalValue: 0.100
maxShotDistanceProperty:
  initialValue: 17.3
  finalValue: 17.3
visualProperties:
  mainProperties:
    - name: Damage
      normalizedValue: 0.5
    - name: Range
      normalizedValue: 0.1
    - name: FireRate
      normalizedValue: 1.00
  properties:
    - name: DPM
      initialValue: 14766
      finalValue: 14766
    - name: Damage per Second
      initialValue: 400
      finalValue: 400
    - name: Healing per Second
      initialValue: 330
      finalValue: 330
    - name: Charge Time
      initialValue: 8
      finalValue: 8
      format: 0.0
      unit: sec
    - name: Reload Time
      initialValue: 7
      finalValue: 7
      format: 0
      unit: sec
    - name: Attack Distance
      initialValue: 17
      finalValue: 17
      unit: m
    - name: SelfHealingAmount
      initialValue: 25
      finalValue: 25
...
